### ISSUE TITLE
The module name does not match the repo name

### ISSUE THREAD

**Issue by akeemphilbert** [OneSignal/onesignal-go-api#5]
The module name is `onesignal-go-client` in the go.mod but the repo name is `onesignal-go-api`. This causes an error 

```
github.com/OneSignal/onesignal-go-api@v1.0.0: parsing go.mod:
        module declares its path as: github.com/OneSignal/onesignal-go-client
                but was required as: github.com/OneSignal/onesignal-go-api
```

I was able to get it installed by doing `go get github.com/OneSignal/onesignal-go-client`. I'm guessing the repo was renamed. If this was intentional then update the instructions here - https://onesignal.com/blog/our-go-client-sdk-is-now-available/

**Comment by rgomezp** [comment]
Howdy @akeemphilbert !
You are exactly right. Thanks for pointing this out. We will get it fixed asap.

**Comment by rgomezp** [comment]
This is now resolved. Thanks
