### ISSUE TITLE
Unable to imprt onesignal

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/onesignal-go-api#7]
I copy and paste the example from this [doc]() and got the following design-time error.

######  Unknown symbol `*openapiclient` 
<img width="1137" alt="Screen Shot 2022-05-27 at 4 29 22 PM" src="https://user-images.githubusercontent.com/1715082/171220830-1a769307-2edf-4c9f-b1e2-196d0f209855.png">

@jmadler mentioned that this could be a typo, so I changed `*openapiclient` to `onesignal` as suggested and got another error stating that onesignal could not be imported. 

###### Unable to import onesignal package
<img width="1814" alt="Screen Shot 2022-05-31 at 11 09 40 AM" src="https://user-images.githubusercontent.com/1715082/171221290-7cf89239-f31e-4278-93a6-762d83a054da.png">

I'm pretty sure I ran the `go get` sub-command, so this may be a bug.

###### go.mod
<img width="1060" alt="Screen Shot 2022-05-31 at 11 15 31 AM" src="https://user-images.githubusercontent.com/1715082/171221720-80355362-06ec-499c-84ec-684ca0dbcc91.png">

**Comment by rgomezp** [comment]
Try importing like so:

```go
package main

import (
	"context"
	"io"
	"math/rand"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/OneSignal/onesignal-go-api"

	"github.com/fatih/color"
)
```

**Comment by iAmWillShepherd** [comment]
That worked!
